ingress:
  enabled: true
maintenance:
  enabled: true
  retryFailed:
    schedule: '* 23 * * *'
  retryPending:
    schedule: '* 23 * * *'
  debug:
    enabled: true
s3-data:
  persistentVolume:
    enabled: false
mongodb-replicaset:
  persistentVolume:
    enabled: false
prometheus:
  rbac:
    create: false
  serviceAccounts:
    alertmanager:
      name: default
      create: false
    nodeExporter:
      name: default
      create: false
    kubeStateMetrics:
      name: default
      create: false
    pushgateway:
      name: default
      create: false
    server:
      name: default
      create: false
  server:
    persistentVolume:
      enabled: false
zenko-queue:
  persistence:
    enabled: false
  rbac:
    enabled: false
zenko-quorum:
  persistence:
    enabled: false
redis-ha:
  persistentVolume:
    enabled: false
  rbac:
    create: false
  serviceAccount:
    create: false
    name: default
global:
  orbit:
    endpoint: http://ciutil-orbit-simulator:4222
    managerMode: poll
    workerMode: poll
cloudserver:
  image:
    pullPolicy: Always
  replicaCount: 3
  replicaFactor: 1
  env:
    MPU_TESTING: 'yes'
    PUSH_STATS: 'false'
backbeat:
  image:
    pullPolicy: Always
    repository: ssalaues/backbeat
    tag: 782d775
  replication:
    replicaFactor: 2
  lifecycle:
    conductor:
      cronRule: 0 */1 * * * *
grafana:
  persistentVolume:
    enabled: false
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  adminUser: admin
  adminPassword: strongpassword
