ingress:
  enabled: true

maintenance:
  # Both options are enabled to test templating
  enabled: true
  retryFailed:
    schedule: "* 23 * * *"
  retryPending:
    schedule: "* 23 * * *"
  debug:
    enabled: true

cosmos:
  ci: true
  storageClass: ci-zenko
  rbac:
    namespaced: true
  operator:
    image:
      pullPolicy: Always
  scheduler:
    image:
      pullPolicy: Always

s3-data:
  persistentVolume:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi


mongodb-replicaset:
  persistentVolume:
    enabled: false
  init:
    timeout: 60
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      cpu: 125m
      memory: 128Mi
  metrics:
    resources: &exporter
      requests:
        cpu: 10m
        memory: 32Mi

prometheus:
  rbac:
    create: false
  serviceAccounts:
    alertmanager:
      name: default
      create: false
    nodeExporter:
      name: default
      create: false
    kubeStateMetrics:
      name: default
      create: false
    pushgateway:
      name: default
      create: false
    server:
      name: default
      create: false
  server:
    persistentVolume:
      enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 128Mi

zenko-queue:
  persistence:
    enabled: false
  rbac:
    enabled: false
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 128Mi

zenko-quorum:
  persistence:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 128Mi
  env:
    ZK_HEAP_SIZE: 2G

redis-ha:
  persistentVolume:
    enabled: false
  rbac:
    create: false
  serviceAccount:
    create: false
    name: default
  redis:
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 64Mi
        cpu: 50m
  sentinel:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
global:
  orbit:
    endpoint: "http://ciutil-orbit-simulator:4222"
    managerMode: "poll"
    workerMode: "poll"

cloudserver:
  image:
    pullPolicy: Always
  replicaCount: 3
  replicaFactor: 1
  env:
    MPU_TESTING: 'yes'
    PUSH_STATS: 'false'
    CI_CEPH: 'true'
    CI: 'true'
    S3_END_TO_END: 'true'
  affinity: ""
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 128Mi
  manager:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 75m
        memory: 128Mi

backbeat:
  image:
    pullPolicy: Always
    repository: ssalaues/backbeat
    tag: 6fead31
  api:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi

  replication:
    dataProcessor:
      resources: &backbeat
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    populator:
      resources: *backbeat
    statusProcessor:
      resources: *backbeat
    retry:
      aws_s3:
        timeoutS: 900
        maxRetries: 5
        backoff:
          min: 2000
          max: 10000
          jitter: 0.1
          factor: 1.5
      azure:
        timeoutS: 900
        maxRetries: 5
        backoff:
          min: 2000
          max: 10000
          jitter: 0.1
          factor: 1.5
      gcp:
        timeoutS: 900
        maxRetries: 5
        backoff:
          min: 2000
          max: 10000
          jitter: 0.1
          factor: 1.5
  lifecycle:
    conductor:
      cronRule: "* * * * *"
      resources: *backbeat
    objectProcessor:
      resources: *backbeat
    bucketProcessor:
      resources: *backbeat
  ingestion:
    consumer:
      resources: *backbeat
    producer:
      resources: *backbeat
  garbageCollector:
    consumer:
      resources: *backbeat

grafana:
  persistentVolume:
    enabled: false
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  adminUser: admin
  adminPassword: strongpassword
